name: CI

on:
  push:
    branches: ["main", "cleanup/remove-sentry-test"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Type Check
        run: npx tsc --noEmit || true
      - name: Run Tests
        run: npm test --if-present
      - name: Build
        run: npm run build --if-present
